include:
  # - board: sparkfun_pro_micro_rp2040
  #   shield: kurp
  - board: nice_nano_v2
    shield: kurp nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
  - board: seeeduino_xiao_rp2040
    shield: hummingbird
