include:
  - board: sparkfun_pro_micro_rp2040
    shield: kurp
  - board: nice_nano_v2
    shield: kurp nice_view_adapter nice_view
  - board: nice_nano_v2 
    shield: kurp nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: settings_reset
